[workspace]
members=[
  "fabrix",
  "fabrix-core",
  "fabrix-json",
  "fabrix-csv",
  "fabrix-parquet",
  "fabrix-xl",
  "fabrix-sql",
  "fabrix-mg",
  "fabrix-mg-derive",
  "fabrix-dyn-conn",
]
exclude=[
  "examples",
]
