[package]
name = "fabrix"
authors = ["JacobX <jacobbishopxy@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.51"
anyhow = "1.0.45"
bigdecimal = "0.3.0"
chrono = { version = "0.4.19", features = ["serde"] }
itertools = "0.10.1"
polars = { version = "0.17.0", features = [
    "strings",
    "serde",
    "parquet",
    "json",
    "dtype-i8",
    "dtype-i16",
    "dtype-u8",
    "dtype-u16",
    "object",
] }
rust_decimal = "1.16.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
lazy_static = "1.4.0"
futures = "0.3.17"

sea-query = { version = "0.18.2", features = [
    "with-chrono",
    "with-json",
    "with-rust_decimal",
    "with-bigdecimal",
    "with-uuid"
], optional = true }
sqlx = { version = "0.5.9", features = [
    "runtime-tokio-native-tls",
    "postgres",
    "mysql",
    "sqlite",
    "chrono",
    "bigdecimal",
    "decimal",
    "uuid"
], optional = true }
thiserror = "1.0.29"
tokio = { version = "1.12.0", features = ["full"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
quick-xml = { version = "0.22.0", features = ["serialize"], optional = true }
zip = { version = "0.5.13", optional = true }
bson2 = { version = "2.0.3", optional = true }
nom = "7.1.0"

[features]
default = ["db", "file", "bson"]
db = ["sea-query", "sqlx"]
file = ["quick-xml", "zip"]
bson = ["bson2"]
