[package]
name = "fabrix"
authors = ["JacobX <jacobbishopxy@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0"
anyhow = "1"
bigdecimal = "0"
chrono = { version = "0", features = ["serde"] }
itertools = "0"
polars = { version = "0", features = [
    "strings",
    "serde",
    "parquet",
    "json",
    "dtype-i8",
    "dtype-i16",
    "dtype-u8",
    "dtype-u16",
    "object",
] }
rust_decimal = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lazy_static = "1"
futures = "0"
nom = "7"

sea-query = { version = "0", features = [
    "with-chrono",
    "with-json",
    "with-rust_decimal",
    "with-bigdecimal",
    "with-uuid"
], optional = true }
sqlx = { version = "0", features = [
    "runtime-tokio-native-tls",
    "postgres",
    "mysql",
    "sqlite",
    "chrono",
    "bigdecimal",
    "decimal",
    "uuid"
], optional = true }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
uuid = { version = "0", features = ["serde", "v4"] }
quick-xml = { version = "0", features = ["serialize"], optional = true }
zip = { version = "0", optional = true }
bson2 = { version = "2", optional = true }

[features]
default = ["sql", "file", "bson", "mgo"]
sql = ["sea-query", "sqlx"]
file = ["quick-xml", "zip"]
bson = ["bson2"]
mgo = []
